# Generated by Django 4.0.4 on 2022-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zamowienia', '0003_alter_daneuzytkownika_ulica'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='ilosc',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
