# Generated by Django 4.0.4 on 2022-06-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zamowienia', '0004_pozycjazamowienia_ilosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daneuzytkownika',
            name='nrMieszkania',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
